spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contas
    username: postgres
    password: postgres
  jpa:
    database-platform=org: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081